"""
Cria/atualiza o webhook do Stripe pra apontar pro backend Cubo / Refine.

Uso:
    cd cubo-backend
    $env:STRIPE_SECRET_KEY="sk_live_..."     # Windows PowerShell (a NOVA chave)
    export STRIPE_SECRET_KEY="sk_live_..."   # Linux/Mac

    python scripts/create_stripe_webhook.py

Opcionalmente passe a URL do webhook:
    python scripts/create_stripe_webhook.py --url https://api.refinecubo.com.br/billing/webhook

Default: https://api.refinecubo.com.br/billing/webhook

Idempotente: se já existe um webhook pro mesmo URL, atualiza os eventos
ao invés de criar duplicado.

Output: imprime o `whsec_...` pra você colar no STRIPE_WEBHOOK_SECRET do .env.
"""
from __future__ import annotations

import argparse
import os
import sys

try:
    import stripe
except ImportError:
    print("ERRO: stripe lib não instalada. Roda: pip install stripe")
    sys.exit(1)


DEFAULT_URL = "https://api.refinecubo.com.br/billing/webhook"

EVENTS = [
    "checkout.session.completed",
    "invoice.paid",
    "customer.subscription.deleted",
]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--url", default=DEFAULT_URL, help="URL do endpoint do webhook")
    args = parser.parse_args()

    secret = os.environ.get("STRIPE_SECRET_KEY", "").strip()
    if not secret:
        print("ERRO: STRIPE_SECRET_KEY não setada.")
        sys.exit(1)
    if not secret.startswith("sk_"):
        print("ERRO: STRIPE_SECRET_KEY parece inválida (use sk_live_ ou sk_test_).")
        sys.exit(1)

    stripe.api_key = secret
    is_test = secret.startswith("sk_test_")
    print(f"\n🔑 Modo: {'TEST 🧪' if is_test else 'LIVE 🔴'}")
    print(f"📡 URL do webhook: {args.url}\n")

    # Procura webhook existente pra mesma URL (idempotência)
    existing = None
    for w in stripe.WebhookEndpoint.list(limit=100).auto_paging_iter():
        if w.url == args.url:
            existing = w
            break

    if existing:
        print(f"⚠️  Já existe webhook pra essa URL (id: {existing.id}). Atualizando eventos...")
        wh = stripe.WebhookEndpoint.modify(
            existing.id,
            enabled_events=EVENTS,
            metadata={"managed_by": "cubo_pricing_script"},
        )
        print(f"✓ Webhook atualizado.")
        print(f"   ID: {wh.id}")
        print(f"   Eventos: {', '.join(wh.enabled_events)}")
        print()
        print("⚠️  O signing secret só é mostrado UMA VEZ na criação.")
        print("   Se você não tem o whsec_ salvo, vai ter que apagar esse webhook")
        print("   no Dashboard e criar um novo. Pra apagar, rode:")
        print(f'   stripe.WebhookEndpoint.delete("{wh.id}")')
        print("   Ou pelo Dashboard → Developers → Webhooks → Delete endpoint")
        return

    # Cria novo
    wh = stripe.WebhookEndpoint.create(
        url=args.url,
        enabled_events=EVENTS,
        description="Cubo / Refine — backend webhook (auto-created)",
        metadata={"managed_by": "cubo_pricing_script"},
    )

    print(f"✓ Webhook criado com sucesso!")
    print(f"  ID: {wh.id}")
    print(f"  Eventos: {', '.join(wh.enabled_events)}\n")

    print("=" * 70)
    print("📋 COLE NO .env DO SERVIDOR:")
    print("=" * 70 + "\n")
    print(f"STRIPE_WEBHOOK_SECRET={wh.secret}")
    print()
    print("⚠️  IMPORTANTE: o whsec_ acima só é mostrado AGORA. Salva ele!")
    print("    Se perder, terá que apagar o webhook e criar de novo.\n")

    # Salva backup local
    backup_path = "scripts/.stripe_webhook_secret.txt"
    with open(backup_path, "w", encoding="utf-8") as f:
        f.write(f"# Generated by create_stripe_webhook.py\n")
        f.write(f"# Webhook URL: {args.url}\n")
        f.write(f"# Webhook ID: {wh.id}\n\n")
        f.write(f"STRIPE_WEBHOOK_SECRET={wh.secret}\n")
    print(f"💾 Backup salvo em: {backup_path}")
    print("⚠️  Esse arquivo está no .gitignore — NÃO commit ele.")


if __name__ == "__main__":
    main()
